### ISSUE TITLE
`parse': undefined method `gsub' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by threepistons** [glennsarti/puppetfile-resolver#10]
- Given: ruby 2.5.5p157 and puppetfile-resolver-0.2.0.
- When I: run the following Ruby script called puppetfile-resolver against Puppetfile in the same directory.
```
#!/usr/bin/ruby

puppetfile_path = 'Puppetfile'

# Parse the Puppetfile into an object model
content = File.open(puppetfile_path, 'rb') { |f| f.read }
require 'puppetfile-resolver'
puppetfile = ::PuppetfileResolver::Puppetfile::Parser::R10KEval.parse(content)

# Make sure the Puppetfile is valid
unless puppetfile.valid?
  puts 'Puppetfile is not valid'
  puppetfile.validation_errors.each { |err| puts err }
  exit 1
end

# Create the resolver
# - Use the document we just parsed (puppetfile)
# - Don't restrict by Puppet version (nil)
resolver = PuppetfileResolver::Resolver.new(puppetfile, nil)

# Configure the resolver
cache                 = nil  # Use the default inmemory cache
ui                    = nil  # Don't output any information
module_paths          = []   # List of paths to search for modules on the local filesystem
allow_missing_modules = true # Allow missing dependencies to be resolved
opts = { cache: cache, ui: ui, module_paths: module_paths, allow_missing_modules: allow_missing_modules }

# Resolve
result = resolver.resolve(opts)

# Output resolution validation errors
result.validation_errors.each { |err| puts "Resolution Validation Error: #{err}\n"}
```
- I get:
```
-> % ./puppetfile-resolver.rb  
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/share/rubygems-integration/all/specifications/erubis-2.7.0.gemspec:16.
Traceback (most recent call last):
        23: from ./puppetfile-resolver.rb:30:in `<main>'
        22: from /home/threepistons/.gem/ruby/2.5.0/gems/puppetfile-resolver-0.2.0/lib/puppetfile-resolver/resolver.rb:36:in `resolve'
        21: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
        20: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
        19: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
        18: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:673:in `attempt_to_activate'
        17: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:702:in `attempt_to_filter_existing_spec'
        16: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:305:in `unwind_for_conflict'
        15: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:335:in `build_details_for_unwind'
        14: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:541:in `binding_requirements_for_conflict'
        13: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:566:in `binding_requirement_in_set?'
        12: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:566:in `any?'
        11: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:567:in `block in binding_requirement_in_set?'
        10: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:486:in `possibility_satisfies_requirements?'
         9: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:486:in `all?'
         8: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:486:in `each'
         7: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:486:in `block in possibility_satisfies_requirements?'
         6: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:24:in `requirement_satisfied_by?'
         5: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
         4: from /home/threepistons/.gem/ruby/2.5.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:25:in `block in requirement_satisfied_by?'
         3: from /home/threepistons/.gem/ruby/2.5.0/gems/puppetfile-resolver-0.2.0/lib/puppetfile-resolver/resolution_provider.rb:94:in `requirement_satisfied_by?'
         2: from /home/threepistons/.gem/ruby/2.5.0/gems/puppetfile-resolver-0.2.0/lib/puppetfile-resolver/models/module_dependency.rb:43:in `satisified_by?'
         1: from /home/threepistons/.gem/ruby/2.5.0/gems/puppetfile-resolver-0.2.0/lib/puppetfile-resolver/models/module_dependency.rb:51:in `semantic_requirement'
/home/threepistons/.gem/ruby/2.5.0/gems/semantic_puppet-1.0.2/lib/semantic_puppet/version_range.rb:66:in `parse': undefined method `gsub' for nil:NilClass (NoMethodError)
```
- I expected: a report about the state of my Puppetfile.

**Comment by glennsarti** [comment]
Hi @threepistons  are you able to also post the Puppetfile you were using to create the bug? Unfortunately it's very difficult to debug without it.

**Comment by threepistons** [comment]
```
## Puppetfile
# This file lives in the control repository

## What this file does
# This file installs modules into each environment on the Puppet master.  A module has to exist in an environment in order for us to use that module.

## What this file doesn't do
# - Apply modules to nodes: the yaml files in data do that, aided by a statement in site.pp
# - Configure modules: the yaml files in data do that, governed by hiera.yaml
# - Resolve and install module dependancies, we have to do that ourselves :sadface:
#   - We can use a tool called generate-puppetfile to resolve dependancies, get it from https://github.com/rnelson0/puppet-generate-puppetfile

# generate-puppetfile explicitly states this even though it's the default forge
forge 'https://forge.puppet.com'

## Forge modules are stated as mod namespace/module, version
# Avoid nasty surprises, use a numeric version and not ":latest" in production

# to manage webhook service on Puppet master, needed for r10k
# mod 'abrader/gms',                           '1.0.3'

# To install Puppet Development Kit on NUIT PCs
mod 'abuxton/pdk',                           '0.2.2'

# dependancy of openldap
mod 'bodgit/bodgitlib',                      '2.0.1'

# used to configure /etc/ldap/ldap.conf
mod 'bodgit/openldap',                       '2.0.4'

# needed for Foreman
mod 'camptocamp/systemd',                    '2.9.0'

# dependancy of mit_krb5
mod 'ccin2p3/etc_services',                  '1.1.1'

# to manage /etc/krb5.conf
mod 'ccin2p3/mit_krb5',                      '1.2.1'

# nfs client and server setup
# This doesn't just provide a custom type for mounts, but also adds the packages and services.
mod 'derdanne/nfs',                          '2.1.4'

# anacron is superior to cron for machines that are regularly turned off
mod 'gearboxscott/anacron',                  '1.0.16'

# dependancy of r10k
mod 'gentoo/portage',                        '2.3.0'

# I forked this to get around a limitation, so comment it out
# mod 'ghoneycutt/hosts',                    '2.6.0'

# Dependancy of types
mod 'ghoneycutt/common',                     '1.9.0'

# This lets us declare lists of packages, files, services, etc in hiera without having to add code to process those lists to site.pp.
mod 'ghoneycutt/types',                      '1.13.0'

# Dependancy of other augeasproviders_*
mod 'herculesteam/augeasproviders_core',     '2.6.0'

# to add password protection to GRUB
mod 'herculesteam/augeasproviders_grub',     '3.2.0'

# needed for derdanne/nfs
mod 'herculesteam/augeasproviders_shellvar', '3.1.0'

# dragged in by generate-puppetfile, don't know what by
mod 'herculesteam/augeasproviders_sysctl',   '2.5.0'

# manage printer queues
mod 'leoarnold/cups',                        '2.2.2'

# dependancy of ca_cert
mod 'lwf/remote_file',                       '1.1.3'

# to manage QuoVadis CA insertion
mod 'pcfens/ca_cert',                        '2.1.2'

# dependancy of pdk
mod 'puppet/archive',                        '3.2.0'

# dependancy of foreman
mod 'puppet/extlib',                         '4.0.0'

# dependancy of r10k
mod 'puppet/make',                           '2.1.0'

# to manage r10k webhooks
mod 'puppet/r10k',                           '6.8.0'

# to manage security upgrades on Ubuntu systems
mod 'puppet/unattended_upgrades',            '5.0.0'

# dependancy of matlab4
mod 'puppet/wget',                           '2.0.1'

# to manage local accounts, e.g. ncsteam and root
mod 'puppetlabs/accounts',                   '3.0.0'

# # dependancy of foreman
mod 'puppetlabs/apache',                     '5.0.0'

# manage apt repos, keys, pins, etc.  Dependancy of foreman
mod 'puppetlabs/apt',                        '7.4.2'

# dependancy of foreman and mit_krb5
mod 'puppetlabs/concat',                     '5.3.0'

# manage firewall entries
mod 'puppetlabs/firewall',                   '2.0.0'

# dependancy of r10k
mod 'puppetlabs/gcc',                        '0.3.0'

# dependancy of r10k
mod 'puppetlabs/git',                        '0.5.0'

# manages inifiles, dependancy of puppet_agent and r10k
mod 'puppetlabs/inifile',                    '3.0.0'

# manage motd and issue
mod 'puppetlabs/motd',                       '2.1.1'

# manage ntp servers
mod 'puppetlabs/ntp',                        '7.2.0'

# dependancy of foreman
mod 'puppetlabs/postgresql',                 '6.1.0'

# manage puppet agent version
mod 'puppetlabs/puppet_agent',               '2.0.1'

# add puppetserver_gem provider, needed for hiera_eyaml_gpg
mod 'puppetlabs/puppetserver_gem',           '1.1.0'

# dependancy for motd even though we don't use windows :eyeroll:
mod 'puppetlabs/registry',                   '2.1.0'

# dependancy of r10k
mod 'puppetlabs/ruby',                       '1.0.0'

# dependancy of ssh
mod 'puppetlabs/sshkeys_core',               '1.0.2'

# dependancy of foreman and a million other things
mod 'puppetlabs/stdlib',                     '6.3.0'

# dependancy of puppet_agent and motd, creates a type called "transition"
mod 'puppetlabs/transition',                 '0.1.1'

# dependancy of foreman via apt
mod 'puppetlabs/translate',                  '2.2.0'

# foreman dep
mod 'puppetlabs/xinetd',                     '3.3.0'

# dependancy of r10k
mod 'puppetlabs/vcsrepo',                    '2.3.0'

mod 'richardc/datacat',                      '0.6.2'

# To manage /etc/sudoers.d files.  Needed for Pis and some Foreman functions.  "Sudo" *group* membership is done by zleslie/groupmembership
mod 'saz/sudo',                              '6.0.0'

# manage SSSD
mod 'sgnl05/sssd',                           '2.9.0'

# manage epel on redhat systems
mod 'stahnma/epel',                          '1.3.1'

# preconfigure matlab-support package, used in matlab4
mod 'stm/debconf',                           '2.3.0'

# manage foreman
mod 'theforeman/dhcp',                       '5.0.1'
mod 'theforeman/dns',                        '6.1.0'
mod 'theforeman/foreman',                    '12.2.0'
mod 'theforeman/foreman_proxy',              '12.0.1'
mod 'theforeman/puppet',                     '12.0.1'
mod 'theforeman/tftp',                       '5.0.1'

# needed for openldap via bodgitlib
mod 'thrnio/ip',                             '1.0.1'

# manage nsswitch
mod 'trlinkin/nsswitch',                     '2.1.0'

# manage members of sudo group
mod 'zleslie/groupmembership',               '1.0.0'

## The following modules are not from the Forge, but are pulled from git repositories
# Generally, git modules should use a named commit or tag, not a branch, to avoid nasty surprises.

# This enables us to encrypt secrets within the Hiera code.
mod 'hiera_eyaml_gpg_installer',
  :git => 'git@gitlab.ncl.ac.uk:puppet5/hiera_eyaml_gpg_installer.git',
  :tag => '1.0.0'

# This is an attempt to provide an ersatz Puppet file server for files that are too big to paste into hiera, too local to put in a module, and too private for cs-ftpmirror.
# Mostly this has held licence files for Matlab.  We don't need these for most Matlab installations now so I am trying to deprecate this.
# It still holds the PPD file for the building printers because it is thousands of lines.
# This declaration, alone of all modules, tracks a branch because we only ever add new files to it, we don't edit the ones already there.
mod 'fileserver',
  :git    => 'git@gitlab.ncl.ac.uk:puppet5/fileserver.git',
  :branch => 'master'

# manages "domain trust" for AD joined machines
mod 'msktutil',
  :git => 'git@gitlab.ncl.ac.uk:puppet5/msktutil.git',
  :tag => '2.0.0'

# This manages the contents of the puppet agent config file, allowing me to enforce certificate name used by the node and the address of the puppet master.
mod 'puppet_agent_conf',
  :git => 'git@gitlab.ncl.ac.uk:puppet5/puppet_agent_conf.git',
  :tag => '1.0.0'

# manage SSH server.  This is a fork of ghoneycutt/ssh to add support for ed25519 keys
mod 'ssh',
  :git    => 'https://github.com/threepistons/puppet-module-ssh.git',
  :commit => '7f0205537cdf81275dc40698826950a781cca31c'

# installs kerberised samba printing backend for cups
mod 'ksmb',
  :git => 'https://ksmb:yi93XMTHiNSoXuyz5xY2@staffcode.ncl.ac.uk/nuit/ncsteam/puppet/modules/ksmb.git',
  :tag => '0.0.3'

# large number of commonly-requested applications, applied per-node on request
mod 'cs_applications',
  :git    => 'git@gitlab.ncl.ac.uk:puppet5/cs_applications.git',
  :commit => 'cb3a389f22719e31718ff925858ef2395c7e4723'

# tools used by NUIT staff, applied per-node on request
mod 'cs_linux_admintools',
  :git => 'git@gitlab.ncl.ac.uk:puppet5/cs_linux_admintools.git',
  :tag => '0.0.3'

# specific neuroinformatics applications, applied per-node on request
mod 'neurosuite',
  :git => 'git@gitlab.ncl.ac.uk:puppet5/neurosuite.git',
  :tag => '0.0.1'

# CuDNN, applied per-node on request
mod 'cudnn',
  :git => 'git@gitlab.ncl.ac.uk:puppet5/cudnn.git',
  :tag => '0.0.1'

# Manages hosts file.  Forked from ghoneycutt/puppet-module-hosts, via blues-man/puppet-module-hosts, to add custom ip for fqdn entry
mod 'hosts',
  :git    => 'https://github.com/threepistons/puppet-module-hosts.git',
  :commit => '7aa29d5e70c3d528ff28ed3fa8317c2aedc01b6b'

# the matlab installer harness, puppet >=4 edition.  Applied per-node on request
mod 'matlab4',
  :git => 'git@gitlab.ncl.ac.uk:puppet5/matlab4.git',
  :tag => '1.0.1'

# Onedrive sync client
mod 'onedrive',
  :git => 'git@gitlab.ncl.ac.uk:puppet5/onedrive.git',
  :tag => '0.0.1'

# Teams client
mod 'teams',
  :git => 'https://puppet5-teams:REDACTEDTOKEN@staffcode.ncl.ac.uk/nuit/ncsteam/puppet/modules/teams.git',
  :tag => '0.0.1'

mod 'grub_lock',
  :git => 'git@gitlab.ncl.ac.uk:puppet5/grub_lock.git',
  :tag => '0.0.3'

mod 'freesurfer',
  :git => 'git@gitlab.ncl.ac.uk:puppet5/freesurfer.git',
  :tag => '0.0.1'

mod 'pidesktop',
  :git => 'https://pidesktop:REDACTEDTOKEN@staffcode.ncl.ac.uk/nuit/ncsteam/puppet/modules/pidesktop.git',
  :tag => '1.2.0'

mod 'piapps',
  :git => 'git@gitlab.ncl.ac.uk:puppet5/piapps.git',
  :tag => '1.1.0'

mod 'derailed_font',
  :git => 'https://gitlab+deploy-token-1:REDACTEDTOKEN@staffcode.ncl.ac.uk/nuit/ncsteam/puppet/modules/derailed_font.git',
  :tag => '1.0.0'
```

**Comment by glennsarti** [comment]
Thanks @threepistons I'll get onto that as soon as I can.

**Comment by glennsarti** [comment]
I can repro the issue.
