### ISSUE TITLE
Issues parsing a Puppetfile

### ISSUE THREAD

**Issue by bdowling** [glennsarti/puppetfile-resolver#40]
I encountered a couple of issues thus far attempting to use your tool, these all seem to be pretty standard syntax to me...

Lines such as ` exclusion 'puppetlabs-inifile'` resulted in:
```
/usr/local/bundle/ruby/2.4.0/gems/puppetfile-resolver-0.4.0/lib/puppetfile-resolver/puppetfile/parser/r10k_eval.rb:35:in `rescue in parse': Unknown method exclusion (PuppetfileResolver::Puppetfile::Parser::ParserError)
        from /usr/local/bundle/ruby/2.4.0/gems/puppetfile-resolver-0.4.0/lib/puppetfile-resolver/puppetfile/parser/r10k_eval.rb:19:in `parse'
        from /usr/local/bundle/ruby/2.4.0/gems/puppetfile-resolver-0.4.0/puppetfile-cli.rb:72:in `<main>'
```

`mod 'elastic-elastic_stack', '<7.0.0'`
```
elastic_stack: Module elastic-elastic_stack with args "<7.0.0" doesn't have an implementation. (Are you using the right arguments?)
```

`
mod 'evenup-rsyslog',
        :path =>  "./public/rsyslog"
`
```
rsyslog: Module evenup-rsyslog with args {:path=>"./public/rsyslog"} doesn't have an implementation. (Are you using the right arguments?)
```

**Comment by glennsarti** [comment]
Are you able to share the entire puppetfile?
